# Generated by Django 5.2.11 on 2026-04-09 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Parqueadero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("capacidad", models.IntegerField()),
                ("ocupancia", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Entrada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("fila", models.IntegerField(default=0)),
                (
                    "parqueadero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parqueadero.parqueadero",
                    ),
                ),
            ],
            options={
                "unique_together": {("parqueadero", "nombre")},
            },
        ),
    ]
