# Generated by Django 5.2.11 on 2026-04-09 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parqueadero", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("codigo_estudiantil", models.CharField(blank=True, max_length=50)),
                (
                    "tipo_usuario",
                    models.CharField(
                        choices=[
                            ("estudiante", "Estudiante"),
                            ("profesor", "Profesor"),
                        ],
                        default="estudiante",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Historial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("hora_entrada", models.TimeField()),
                ("hora_salida", models.TimeField(blank=True, null=True)),
                ("costo", models.IntegerField(default=0)),
                (
                    "entrada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="parqueadero.entrada",
                    ),
                ),
                (
                    "parqueadero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parqueadero.parqueadero",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parqueadero.perfilusuario",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha", "-hora_entrada"],
            },
        ),
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("placa", models.CharField(max_length=20, unique=True)),
                ("marca", models.CharField(max_length=50)),
                ("modelo", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=30)),
                (
                    "tipo_vehiculo",
                    models.CharField(
                        choices=[("carro", "Carro"), ("moto", "Moto")], max_length=20
                    ),
                ),
                ("es_electrico", models.BooleanField(default=False)),
                ("precio_diario", models.IntegerField(default=0)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parqueadero.perfilusuario",
                    ),
                ),
            ],
        ),
    ]
