# Generated by Django 5.2.11 on 2026-05-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parqueadero", "0002_perfilusuario_historial_vehiculo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfilusuario",
            name="tipo_usuario",
            field=models.CharField(
                choices=[
                    ("estudiante", "Estudiante"),
                    ("profesor", "Profesor"),
                    ("trabajador", "Trabajador"),
                ],
                default="estudiante",
                max_length=20,
            ),
        ),
    ]
