# Generated by Codex on 2026-05-09

from django.db import migrations, models


def create_professor_parking(apps, schema_editor):
    Parqueadero = apps.get_model("parqueadero", "Parqueadero")
    Entrada = apps.get_model("parqueadero", "Entrada")

    parqueadero, _ = Parqueadero.objects.get_or_create(
        nombre="Profesores",
        defaults={
            "capacidad": 50,
            "ocupancia": 0,
            "tipo_acceso": "profesores",
        },
    )
    parqueadero.capacidad = 50
    parqueadero.tipo_acceso = "profesores"
    parqueadero.save(update_fields=["capacidad", "tipo_acceso"])

    Entrada.objects.get_or_create(nombre="Regional", parqueadero=parqueadero)
    Entrada.objects.get_or_create(nombre="Las Vegas", parqueadero=parqueadero)


class Migration(migrations.Migration):

    dependencies = [
        ("parqueadero", "0003_alter_perfilusuario_tipo_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="parqueadero",
            name="tipo_acceso",
            field=models.CharField(
                choices=[("general", "General"), ("profesores", "Solo profesores")],
                default="general",
                max_length=20,
            ),
        ),
        migrations.RunPython(create_professor_parking, migrations.RunPython.noop),
    ]
