# Generated by Codex on 2026-05-09

from django.db import migrations


def _base_entrance_name(name):
    base_name = name.split("(", 1)[0].strip()
    if base_name.lower().startswith("entrada "):
        base_name = base_name[8:].strip()
    return base_name or name.strip()


def specify_entrance_parking_names(apps, schema_editor):
    Entrada = apps.get_model("parqueadero", "Entrada")

    for entrada in Entrada.objects.select_related("parqueadero"):
        base_name = _base_entrance_name(entrada.nombre)
        entrada.nombre = f"{base_name} ({entrada.parqueadero.nombre})"
        entrada.save(update_fields=["nombre"])


def unspecify_entrance_parking_names(apps, schema_editor):
    Entrada = apps.get_model("parqueadero", "Entrada")

    for entrada in Entrada.objects.all():
        entrada.nombre = _base_entrance_name(entrada.nombre)
        entrada.save(update_fields=["nombre"])


class Migration(migrations.Migration):

    dependencies = [
        ("parqueadero", "0004_parqueadero_tipo_acceso_profesores"),
    ]

    operations = [
        migrations.RunPython(specify_entrance_parking_names, unspecify_entrance_parking_names),
    ]
