# Generated by Codex on 2026-05-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parqueadero", "0005_specify_entrance_parking_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvisoEnCamino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eta_minutos", models.IntegerField()),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("llegada_estimada", models.DateTimeField()),
                ("agregado_a_fila", models.BooleanField(default=False)),
                (
                    "entrada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parqueadero.entrada",
                    ),
                ),
                (
                    "parqueadero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parqueadero.parqueadero",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parqueadero.perfilusuario",
                    ),
                ),
            ],
            options={
                "ordering": ["-creado_en"],
            },
        ),
    ]
