# Generated by Codex on 2026-05-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parqueadero", "0006_avisoencamino"),
    ]

    operations = [
        migrations.AddField(
            model_name="avisoencamino",
            name="cancelado",
            field=models.BooleanField(default=False),
        ),
    ]
