# Generated by Django 5.2.11 on 2026-05-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0007_avisoencamino_cancelado'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.CharField(max_length=100)),
                ('marca', models.CharField(default='Tarjeta', max_length=40)),
                ('ultimos_cuatro', models.CharField(max_length=4)),
                ('mes_expiracion', models.PositiveSmallIntegerField()),
                ('anio_expiracion', models.PositiveSmallIntegerField()),
                ('es_activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pago', to='parqueadero.perfilusuario')),
            ],
            options={
                'ordering': ['-es_activa', '-actualizado_en'],
            },
        ),
    ]
