TRANSLATIONS = {
    "es": {
        "welcome": "Bienvenido a FlowGate",
        "weather": "Estado del clima",
        "congestion": "Congestion vehicular",
        "parking_status": "Estado de los parqueaderos",
        "capacity": "Capacidad",
        "occupancy": "Ocupancia",
        "entrance": "Entrada",
        "queue": "Fila",
        "waiting_time": "Tiempo de espera",
        "minutes": "minutos",
        "payments": "Pagos",
        "login": "Iniciar sesion",
        "logout": "Cerrar sesion",
        "profile": "Perfil",
        "history": "Historial",
        "signup": "Registrarse",
        "language": "Idioma",
        "select_language": "Selecciona un idioma",
        "sunny": "Soleado",
        "rainy": "Lluvioso",
        "cloudy": "Nublado",
        "stormy": "Tormentoso",
        "low": "Baja",
        "moderate": "Moderada",
        "high": "Alta",
        "user_info": "Informacion del usuario",
        "vehicle_info": "Informacion del vehiculo",
        "email": "Correo electronico",
        "phone": "Telefono",
        "student_code": "Codigo estudiantil",
        "teacher_code": "Codigo de profesor",
        "worker_code": "Codigo de trabajador",
        "user_type": "Tipo de usuario",
        "plate": "Placa",
        "brand": "Marca",
        "model": "Modelo",
        "color": "Color",
        "vehicle_type": "Tipo de vehiculo",
        "electric": "Electrico",
        "daily_price": "Precio diario",
        "free": "Gratis",
        "dashboard": "Dashboard",
        "on_the_way": "En camino",
        "update": "Actualizar",
        "edit": "Editar",
        "delete": "Eliminar",
        "delete_account": "Eliminar cuenta",
        "delete_vehicle": "Eliminar vehiculo",
        "save_changes": "Guardar cambios",
        "full_name": "Nombre completo",
        "personal_info": "Informacion personal",
        "registered_vehicle": "Vehiculo registrado",
        "account_settings": "Configuracion de cuenta",
        "create_vehicle": "Registrar vehiculo",
        "current_rate": "Tarifa actual",
        "available": "disponibles",
        "occupied": "ocupado",
        "updated_at": "Ultima actualizacion",
        "summary": "Resumen general",
        "total_slots": "Espacios totales",
        "occupied_slots": "Espacios ocupados",
        "available_slots": "Espacios disponibles",
        "avg_speed": "Velocidad promedio",
        "status": "Estado",
        "full": "Lleno",
        "moderate_label": "Moderado",
        "almost_full": "Casi lleno",
        "fluid": "Fluido",
        "consider_options": "Considera tus opciones",
        "recommendation_text": "Puedes venir en auto, pero hay algunas condiciones que podrian afectar tu viaje.",
        "eta": "Tiempo estimado de llegada",
        "select_destination": "Selecciona tu parqueadero de destino",
        "start_trip": "Iniciar viaje",
        "important_info": "Informacion importante",
        "rates": "Tarifas",
        "balance": "Saldo disponible",
        "recharge": "Recargar",
        "payment_history": "Historial",
        "manage_balance": "Gestiona tu saldo y realiza pagos de parqueadero",
        "history_title": "Registro de entradas y salidas",
        "active": "Activo",
        "account_deleted": "Tu cuenta fue eliminada correctamente.",
        "profile_updated": "Tu informacion fue actualizada correctamente.",
        "vehicle_updated": "La informacion del vehiculo fue actualizada correctamente.",
        "vehicle_deleted": "El vehiculo fue eliminado correctamente.",
        "errors_found": "Revisa los campos e intenta de nuevo.",
        "simulated_balance": "Este modulo presenta una simulacion de saldo y tarifas.",
        "real_time_dashboard": "Dashboard en tiempo real",
        "humidity": "Humedad",
        "wind": "Viento",
        "entry_status": "Estado de Entradas",
        "in_queue": "en fila",
        "no_queue": "sin fila",
        "parking_rates_title": "Tarifas de parqueadero",
        "information": "Informacion",
        "payment_title": "Pagos y Saldo",
        "payment_method": "Metodo de pago",
        "payment_method_title": "Tarjeta para pagos",
        "payment_method_subtitle": "Agrega una tarjeta para futuras recargas y pagos del parqueadero.",
        "public_rates_intro": "Consulta las tarifas disponibles del parqueadero.",
        "recharge_placeholder": "Monto a recargar",
        "saved_payment_method": "Tarjeta guardada",
        "no_payment_method": "Aun no tienes una tarjeta guardada.",
        "card_number": "Numero de tarjeta",
        "cardholder_name": "Nombre del titular",
        "card_expiry": "Vencimiento",
        "card_cvv": "CVV",
        "save_card": "Guardar tarjeta y efectuar pago",
        "cancel_recharge": "Cancelar recarga",
        "back_to_card": "Volver a la tarjeta",
        "card_secure_note": "Solo guardamos la marca, el vencimiento y los ultimos 4 digitos. El CVV no se almacena.",
        "card_saved": "Metodo de pago guardado correctamente.",
        "card_invalid": "Revisa los datos de la tarjeta e intenta de nuevo.",
        "card_ending": "terminada en",
        "expires": "Vence",
        "history_entry_time": "Entrada",
        "history_exit_time": "Salida",
        "no_history": "No hay registros de entradas y salidas aun.",
        "no_history_short": "Sin registros aun",
        "no_profile_history": "No hay registros de historial todavia.",
        "delete_account_warning": "Si eliminas la cuenta, tambien se eliminaran tus datos asociados, tu vehiculo y tu historial.",
        "student": "Estudiante",
        "teacher": "Profesor",
        "worker": "Trabajador",
        "username": "Usuario",
        "password": "Contrasena",
        "car": "Automovil",
        "motorcycle": "Motocicleta",
        "per_day": "/ dia",
        "per_hour": "/ hora",
        "student_car_title": "Estudiante - Automovil",
        "student_car_description": "Tarifa diaria para estudiantes con automovil convencional",
        "personal_car_title": "Personal - Automovil",
        "personal_car_description": "Tarifa diaria para profesores, trabajadores y administradores",
        "student_motorcycle_title": "Estudiante - Motocicleta",
        "student_motorcycle_description": "Tarifa diaria para estudiantes con motocicleta",
        "visitor_car_title": "Visitante - Automovil",
        "visitor_car_description": "Tarifa por hora para visitantes",
        "electric_vehicle_title": "Vehiculo Electrico",
        "electric_vehicle_description": "Sin cargo para vehiculos electricos",
        "payment_rule_1": "El cobro se realiza automaticamente al salir del parqueadero.",
        "payment_rule_2": "La primera hora o fraccion se cobra completa.",
        "payment_rule_3": "El sistema calcula el tiempo exacto de permanencia.",
        "payment_rule_4": "Asegurate de tener saldo suficiente antes de ingresar.",
        "eta_note": "Nota: El sistema ajustara automaticamente la disponibilidad basandose en tu tiempo estimado de llegada.",
        "on_the_way_subtitle": "Avisa que vas en camino para obtener mejor informacion y reservar tu espacio.",
        "trip_started_title": "Viaje iniciado",
        "trip_started_text": "Tu llegada fue registrada y ajustamos la disponibilidad proyectada para tu destino.",
        "selected_destination": "Destino seleccionado",
        "trip_initialized": "Viaje inicializado",
        "cancel_trip": "Cancelar viaje",
        "trip_cancelled": "Viaje cancelado correctamente.",
        "select_valid_entry": "Selecciona una entrada valida para avisar que vas en camino.",
        "select_available_parking_entry": "Selecciona un parqueadero y una entrada disponibles para tu usuario.",
        "availability": "Disponibilidad",
        "current_queue": "Fila actual",
        "estimated_arrival": "Llegada estimada",
    },
    "en": {
        "welcome": "Welcome to FlowGate",
        "weather": "Weather status",
        "congestion": "Vehicle congestion",
        "parking_status": "Parking status",
        "capacity": "Capacity",
        "occupancy": "Occupancy",
        "entrance": "Entrance",
        "queue": "Queue",
        "waiting_time": "Waiting time",
        "minutes": "minutes",
        "payments": "Payments",
        "login": "Log in",
        "logout": "Log out",
        "profile": "Profile",
        "history": "History",
        "signup": "Sign up",
        "language": "Language",
        "select_language": "Select a language",
        "sunny": "Sunny",
        "rainy": "Rainy",
        "cloudy": "Cloudy",
        "stormy": "Stormy",
        "low": "Low",
        "moderate": "Moderate",
        "high": "High",
        "user_info": "User information",
        "vehicle_info": "Vehicle information",
        "email": "Email",
        "phone": "Phone",
        "student_code": "Student code",
        "teacher_code": "Teacher code",
        "worker_code": "Worker code",
        "user_type": "User type",
        "plate": "License plate",
        "brand": "Brand",
        "model": "Model",
        "color": "Color",
        "vehicle_type": "Vehicle type",
        "electric": "Electric",
        "daily_price": "Daily price",
        "free": "Free",
        "dashboard": "Dashboard",
        "on_the_way": "On the way",
        "update": "Update",
        "edit": "Edit",
        "delete": "Delete",
        "delete_account": "Delete account",
        "delete_vehicle": "Delete vehicle",
        "save_changes": "Save changes",
        "full_name": "Full name",
        "personal_info": "Personal information",
        "registered_vehicle": "Registered vehicle",
        "account_settings": "Account settings",
        "create_vehicle": "Register vehicle",
        "current_rate": "Current rate",
        "available": "available",
        "occupied": "occupied",
        "updated_at": "Last update",
        "summary": "Overall summary",
        "total_slots": "Total slots",
        "occupied_slots": "Occupied slots",
        "available_slots": "Available slots",
        "avg_speed": "Average speed",
        "status": "Status",
        "full": "Full",
        "moderate_label": "Moderate",
        "almost_full": "Almost full",
        "fluid": "Fluid",
        "consider_options": "Consider your options",
        "recommendation_text": "You can still drive in, but some conditions may affect your trip.",
        "eta": "Estimated arrival time",
        "select_destination": "Select your destination parking lot",
        "start_trip": "Start trip",
        "important_info": "Important information",
        "rates": "Rates",
        "balance": "Available balance",
        "recharge": "Recharge",
        "payment_history": "History",
        "manage_balance": "Manage your balance and make parking payments",
        "history_title": "Entry and exit log",
        "active": "Active",
        "account_deleted": "Your account was deleted successfully.",
        "profile_updated": "Your information was updated successfully.",
        "vehicle_updated": "Vehicle information was updated successfully.",
        "vehicle_deleted": "Vehicle was deleted successfully.",
        "errors_found": "Please review the fields and try again.",
        "simulated_balance": "This module presents a balance and tariff simulation.",
        "real_time_dashboard": "Real-time dashboard",
        "humidity": "Humidity",
        "wind": "Wind",
        "entry_status": "Entry Status",
        "in_queue": "in queue",
        "no_queue": "no queue",
        "parking_rates_title": "Parking rates",
        "information": "Information",
        "payment_title": "Payments and Balance",
        "payment_method": "Payment method",
        "payment_method_title": "Payment card",
        "payment_method_subtitle": "Add a card for future top-ups and parking payments.",
        "public_rates_intro": "Check the available parking rates.",
        "recharge_placeholder": "Recharge amount",
        "saved_payment_method": "Saved card",
        "no_payment_method": "You do not have a saved card yet.",
        "card_number": "Card number",
        "cardholder_name": "Cardholder name",
        "card_expiry": "Expiry",
        "card_cvv": "CVV",
        "save_card": "Save card and pay",
        "cancel_recharge": "Cancel recharge",
        "back_to_card": "Back to card",
        "card_secure_note": "We only store the brand, expiry date, and last 4 digits. CVV is not stored.",
        "card_saved": "Payment method saved successfully.",
        "card_invalid": "Review the card details and try again.",
        "card_ending": "ending in",
        "expires": "Expires",
        "history_entry_time": "Entry",
        "history_exit_time": "Exit",
        "no_history": "There are no entry and exit records yet.",
        "no_history_short": "No records yet",
        "no_profile_history": "There is no history yet.",
        "delete_account_warning": "If you delete your account, your related data, vehicle, and history will also be deleted.",
        "student": "Student",
        "teacher": "Professor",
        "worker": "Worker",
        "username": "Username",
        "password": "Password",
        "car": "Car",
        "motorcycle": "Motorcycle",
        "per_day": "/ day",
        "per_hour": "/ hour",
        "student_car_title": "Student - Car",
        "student_car_description": "Daily rate for students with a standard car",
        "personal_car_title": "Staff - Car",
        "personal_car_description": "Daily rate for professors, workers, and administrators",
        "student_motorcycle_title": "Student - Motorcycle",
        "student_motorcycle_description": "Daily rate for students with a motorcycle",
        "visitor_car_title": "Visitor - Car",
        "visitor_car_description": "Hourly rate for visitors",
        "electric_vehicle_title": "Electric Vehicle",
        "electric_vehicle_description": "No charge for electric vehicles",
        "payment_rule_1": "Charges are applied automatically when leaving the parking lot.",
        "payment_rule_2": "The first hour or fraction is charged in full.",
        "payment_rule_3": "The system calculates the exact time of stay.",
        "payment_rule_4": "Make sure you have enough balance before entering.",
        "eta_note": "Note: The system will automatically adjust availability based on your estimated arrival time.",
        "on_the_way_subtitle": "Let the system know you are on your way to get better information and reserve your spot.",
        "trip_started_title": "Trip started",
        "trip_started_text": "Your arrival was registered and projected availability was adjusted for your destination.",
        "selected_destination": "Selected destination",
        "trip_initialized": "Trip initialized",
        "cancel_trip": "Cancel trip",
        "trip_cancelled": "Trip cancelled successfully.",
        "select_valid_entry": "Select a valid entrance to let the system know you are on your way.",
        "select_available_parking_entry": "Select a parking lot and entrance available for your user.",
        "availability": "Availability",
        "current_queue": "Current queue",
        "estimated_arrival": "Estimated arrival",
    },
}


def get_translation(lang, key):
    return TRANSLATIONS.get(lang, TRANSLATIONS["es"]).get(key, key)


PARKING_NAME_TRANSLATIONS = {
    "Principal": {"es": "Principal", "en": "Main"},
    "Idiomas": {"es": "Idiomas", "en": "Languages"},
    "Ingenieros": {"es": "Ingenieros", "en": "Engineering"},
    "Profesores": {"es": "Profesores", "en": "Faculty"},
}

ENTRANCE_NAME_TRANSLATIONS = {
    "Entrada Principal": {"es": "Entrada Principal", "en": "Main Entrance"},
    "Principal": {"es": "Principal", "en": "Main"},
    "Las Vegas": {"es": "Las Vegas", "en": "Las Vegas"},
    "Regional": {"es": "Regional", "en": "Regional"},
    "Norte": {"es": "Norte", "en": "North"},
    "Sur": {"es": "Sur", "en": "South"},
    "Entrada Norte": {"es": "Entrada Norte", "en": "North Entrance"},
    "Entrada Sur": {"es": "Entrada Sur", "en": "South Entrance"},
}


def translate_parking_name(name, lang):
    return PARKING_NAME_TRANSLATIONS.get(name, {}).get(lang, name)


def translate_entrance_name(name, lang):
    return ENTRANCE_NAME_TRANSLATIONS.get(name, {}).get(lang, name)


def get_lang(request):
    lang = request.GET.get("lang", request.session.get("lang", "es"))
    if lang not in {"es", "en"}:
        lang = "es"
    request.session["lang"] = lang
    return lang

