TRANSLATIONS = {
    "es": {
        "welcome": "Bienvenido a FlowGate",
        "weather": "Estado del Clima",
        "congestion": "Congestion Vehicular",
        "parking_status": "Estado de los Parqueaderos",
        "capacity": "Capacidad",
        "occupancy": "Ocupancia",
        "entrance": "Entrada",
        "queue": "Fila",
        "waiting_time": "Tiempo de espera",
        "minutes": "minutos",
        "payments": "Pagos",
        "login": "Iniciar Sesion",
        "logout": "Cerrar Sesion",
        "profile": "Perfil",
        "history": "Historial",
        "signup": "Registrarse",
        "language": "Idioma",
        "select_language": "Selecciona un idioma",
        "sunny": "Soleado",
        "rainy": "Lluvioso",
        "cloudy": "Nublado",
        "stormy": "Tormentoso",
        "low": "Baja",
        "moderate": "Moderada",
        "high": "Alta",
        "user_info": "Informacion del Usuario",
        "vehicle_info": "Informacion del Vehiculo",
        "email": "Correo Electronico",
        "phone": "Telefono",
        "student_code": "Codigo Estudiantil",
        "user_type": "Tipo de Usuario",
        "plate": "Placa",
        "brand": "Marca",
        "model": "Modelo",
        "color": "Color",
        "vehicle_type": "Tipo de Vehiculo",
        "electric": "Electrico",
        "daily_price": "Precio Diario",
        "free": "Gratis",
        "dashboard": "Dashboard",
        "on_the_way": "En Camino",
        "update": "Actualizar",
        "edit": "Editar",
        "delete": "Eliminar",
        "delete_account": "Eliminar Cuenta",
        "delete_vehicle": "Eliminar Vehiculo",
        "save_changes": "Guardar Cambios",
        "full_name": "Nombre Completo",
        "personal_info": "Informacion Personal",
        "registered_vehicle": "Vehiculo Registrado",
        "account_settings": "Configuracion de Cuenta",
        "create_vehicle": "Registrar Vehiculo",
        "current_rate": "Tarifa Actual",
        "available": "disponibles",
        "occupied": "ocupado",
        "updated_at": "Ultima actualizacion",
        "summary": "Resumen General",
        "total_slots": "Espacios Totales",
        "occupied_slots": "Espacios Ocupados",
        "available_slots": "Espacios Disponibles",
        "avg_speed": "Velocidad Promedio",
        "status": "Estado",
        "moderate_label": "Moderado",
        "almost_full": "Casi Lleno",
        "fluid": "Fluido",
        "consider_options": "Considera tus opciones",
        "recommendation_text": "Puedes venir en auto, pero hay algunas condiciones que podrian afectar tu viaje.",
        "eta": "Tiempo Estimado de Llegada",
        "select_destination": "Selecciona tu Parqueadero de Destino",
        "start_trip": "Iniciar Viaje",
        "important_info": "Informacion Importante",
        "rates": "Tarifas",
        "balance": "Saldo Disponible",
        "recharge": "Recargar",
        "payment_history": "Historial",
        "manage_balance": "Gestiona tu saldo y realiza pagos de parqueadero",
        "history_title": "Registro de Entradas y Salidas",
        "active": "Activo",
        "account_deleted": "Tu cuenta fue eliminada correctamente.",
        "profile_updated": "Tu informacion fue actualizada correctamente.",
        "vehicle_updated": "La informacion del vehiculo fue actualizada correctamente.",
        "vehicle_deleted": "El vehiculo fue eliminado correctamente.",
        "errors_found": "Revisa los campos e intenta de nuevo.",
        "simulated_balance": "Este modulo presenta una simulacion de saldo y tarifas.",
    },
    "en": {
        "welcome": "Welcome to FlowGate",
        "weather": "Weather Status",
        "congestion": "Vehicle Congestion",
        "parking_status": "Parking Status",
        "capacity": "Capacity",
        "occupancy": "Occupancy",
        "entrance": "Entrance",
        "queue": "Queue",
        "waiting_time": "Waiting Time",
        "minutes": "minutes",
        "payments": "Payments",
        "login": "Log In",
        "logout": "Log Out",
        "profile": "Profile",
        "history": "History",
        "signup": "Sign Up",
        "language": "Language",
        "select_language": "Select a language",
        "sunny": "Sunny",
        "rainy": "Rainy",
        "cloudy": "Cloudy",
        "stormy": "Stormy",
        "low": "Low",
        "moderate": "Moderate",
        "high": "High",
        "user_info": "User Information",
        "vehicle_info": "Vehicle Information",
        "email": "Email",
        "phone": "Phone",
        "student_code": "Student Code",
        "user_type": "User Type",
        "plate": "License Plate",
        "brand": "Brand",
        "model": "Model",
        "color": "Color",
        "vehicle_type": "Vehicle Type",
        "electric": "Electric",
        "daily_price": "Daily Price",
        "free": "Free",
        "dashboard": "Dashboard",
        "on_the_way": "On The Way",
        "update": "Update",
        "edit": "Edit",
        "delete": "Delete",
        "delete_account": "Delete Account",
        "delete_vehicle": "Delete Vehicle",
        "save_changes": "Save Changes",
        "full_name": "Full Name",
        "personal_info": "Personal Information",
        "registered_vehicle": "Registered Vehicle",
        "account_settings": "Account Settings",
        "create_vehicle": "Register Vehicle",
        "current_rate": "Current Rate",
        "available": "available",
        "occupied": "occupied",
        "updated_at": "Last update",
        "summary": "Overall Summary",
        "total_slots": "Total Slots",
        "occupied_slots": "Occupied Slots",
        "available_slots": "Available Slots",
        "avg_speed": "Average Speed",
        "status": "Status",
        "moderate_label": "Moderate",
        "almost_full": "Almost Full",
        "fluid": "Fluid",
        "consider_options": "Consider your options",
        "recommendation_text": "You can still drive in, but some conditions may affect your trip.",
        "eta": "Estimated Arrival Time",
        "select_destination": "Select Your Destination Parking Lot",
        "start_trip": "Start Trip",
        "important_info": "Important Information",
        "rates": "Rates",
        "balance": "Available Balance",
        "recharge": "Recharge",
        "payment_history": "History",
        "manage_balance": "Manage your balance and make parking payments",
        "history_title": "Entry and Exit Log",
        "active": "Active",
        "account_deleted": "Your account was deleted successfully.",
        "profile_updated": "Your information was updated successfully.",
        "vehicle_updated": "Vehicle information was updated successfully.",
        "vehicle_deleted": "Vehicle was deleted successfully.",
        "errors_found": "Please review the fields and try again.",
        "simulated_balance": "This module presents a balance and tariff simulation.",
    },
}


def get_translation(lang, key):
    return TRANSLATIONS.get(lang, TRANSLATIONS["es"]).get(key, key)


def get_lang(request):
    lang = request.GET.get("lang", request.session.get("lang", "es"))
    if lang not in {"es", "en"}:
        lang = "es"
    request.session["lang"] = lang
    return lang

