TRANSLATIONS = {
    "es": {
        "welcome": "Bienvenido a FlowGate",
        "weather": "Estado del clima",
        "congestion": "Congestion vehicular",
        "parking_status": "Estado de los parqueaderos",
        "capacity": "Capacidad",
        "occupancy": "Ocupancia",
        "entrance": "Entrada",
        "queue": "Fila",
        "waiting_time": "Tiempo de espera",
        "minutes": "minutos",
        "payments": "Pagos",
        "login": "Iniciar sesion",
        "logout": "Cerrar sesion",
        "profile": "Perfil",
        "history": "Historial",
        "signup": "Registrarse",
        "language": "Idioma",
        "select_language": "Selecciona un idioma",
        "sunny": "Soleado",
        "rainy": "Lluvioso",
        "cloudy": "Nublado",
        "stormy": "Tormentoso",
        "low": "Baja",
        "moderate": "Moderada",
        "high": "Alta",
        "user_info": "Informacion del usuario",
        "vehicle_info": "Informacion del vehiculo",
        "email": "Correo electronico",
        "phone": "Telefono",
        "student_code": "Codigo estudiantil",
        "teacher_code": "Codigo de profesor",
        "worker_code": "Codigo de trabajador",
        "user_type": "Tipo de usuario",
        "plate": "Placa",
        "brand": "Marca",
        "model": "Modelo",
        "color": "Color",
        "vehicle_type": "Tipo de vehiculo",
        "electric": "Electrico",
        "daily_price": "Precio diario",
        "free": "Gratis",
        "dashboard": "Dashboard",
        "on_the_way": "En camino",
        "update": "Actualizar",
        "edit": "Editar",
        "delete": "Eliminar",
        "delete_account": "Eliminar cuenta",
        "delete_vehicle": "Eliminar vehiculo",
        "save_changes": "Guardar cambios",
        "full_name": "Nombre completo",
        "personal_info": "Informacion personal",
        "registered_vehicle": "Vehiculo registrado",
        "account_settings": "Configuracion de cuenta",
        "create_vehicle": "Registrar vehiculo",
        "current_rate": "Tarifa actual",
        "available": "disponibles",
        "occupied": "ocupado",
        "updated_at": "Ultima actualizacion",
        "summary": "Resumen general",
        "total_slots": "Espacios totales",
        "occupied_slots": "Espacios ocupados",
        "available_slots": "Espacios disponibles",
        "avg_speed": "Velocidad promedio",
        "status": "Estado",
        "full": "Lleno",
        "moderate_label": "Moderado",
        "almost_full": "Casi lleno",
        "fluid": "Fluido",
        "consider_options": "Considera tus opciones",
        "recommendation_text": "Puedes venir en auto, pero hay algunas condiciones que podrian afectar tu viaje.",
        "eta": "Tiempo estimado de llegada",
        "select_destination": "Selecciona tu parqueadero de destino",
        "start_trip": "Iniciar viaje",
        "important_info": "Informacion importante",
        "rates": "Tarifas",
        "balance": "Saldo disponible",
        "recharge": "Recargar",
        "payment_history": "Historial",
        "manage_balance": "Gestiona tu saldo y realiza pagos de parqueadero",
        "history_title": "Registro de entradas y salidas",
        "active": "Activo",
        "account_deleted": "Tu cuenta fue eliminada correctamente.",
        "profile_updated": "Tu informacion fue actualizada correctamente.",
        "vehicle_updated": "La informacion del vehiculo fue actualizada correctamente.",
        "vehicle_deleted": "El vehiculo fue eliminado correctamente.",
        "errors_found": "Revisa los campos e intenta de nuevo.",
        "simulated_balance": "Este modulo presenta una simulacion de saldo y tarifas.",
    },
    "en": {
        "welcome": "Welcome to FlowGate",
        "weather": "Weather status",
        "congestion": "Vehicle congestion",
        "parking_status": "Parking status",
        "capacity": "Capacity",
        "occupancy": "Occupancy",
        "entrance": "Entrance",
        "queue": "Queue",
        "waiting_time": "Waiting time",
        "minutes": "minutes",
        "payments": "Payments",
        "login": "Log in",
        "logout": "Log out",
        "profile": "Profile",
        "history": "History",
        "signup": "Sign up",
        "language": "Language",
        "select_language": "Select a language",
        "sunny": "Sunny",
        "rainy": "Rainy",
        "cloudy": "Cloudy",
        "stormy": "Stormy",
        "low": "Low",
        "moderate": "Moderate",
        "high": "High",
        "user_info": "User information",
        "vehicle_info": "Vehicle information",
        "email": "Email",
        "phone": "Phone",
        "student_code": "Student code",
        "teacher_code": "Teacher code",
        "worker_code": "Worker code",
        "user_type": "User type",
        "plate": "License plate",
        "brand": "Brand",
        "model": "Model",
        "color": "Color",
        "vehicle_type": "Vehicle type",
        "electric": "Electric",
        "daily_price": "Daily price",
        "free": "Free",
        "dashboard": "Dashboard",
        "on_the_way": "On the way",
        "update": "Update",
        "edit": "Edit",
        "delete": "Delete",
        "delete_account": "Delete account",
        "delete_vehicle": "Delete vehicle",
        "save_changes": "Save changes",
        "full_name": "Full name",
        "personal_info": "Personal information",
        "registered_vehicle": "Registered vehicle",
        "account_settings": "Account settings",
        "create_vehicle": "Register vehicle",
        "current_rate": "Current rate",
        "available": "available",
        "occupied": "occupied",
        "updated_at": "Last update",
        "summary": "Overall summary",
        "total_slots": "Total slots",
        "occupied_slots": "Occupied slots",
        "available_slots": "Available slots",
        "avg_speed": "Average speed",
        "status": "Status",
        "full": "Full",
        "moderate_label": "Moderate",
        "almost_full": "Almost full",
        "fluid": "Fluid",
        "consider_options": "Consider your options",
        "recommendation_text": "You can still drive in, but some conditions may affect your trip.",
        "eta": "Estimated arrival time",
        "select_destination": "Select your destination parking lot",
        "start_trip": "Start trip",
        "important_info": "Important information",
        "rates": "Rates",
        "balance": "Available balance",
        "recharge": "Recharge",
        "payment_history": "History",
        "manage_balance": "Manage your balance and make parking payments",
        "history_title": "Entry and exit log",
        "active": "Active",
        "account_deleted": "Your account was deleted successfully.",
        "profile_updated": "Your information was updated successfully.",
        "vehicle_updated": "Vehicle information was updated successfully.",
        "vehicle_deleted": "Vehicle was deleted successfully.",
        "errors_found": "Please review the fields and try again.",
        "simulated_balance": "This module presents a balance and tariff simulation.",
    },
}


def get_translation(lang, key):
    return TRANSLATIONS.get(lang, TRANSLATIONS["es"]).get(key, key)


def get_lang(request):
    lang = request.GET.get("lang", request.session.get("lang", "es"))
    if lang not in {"es", "en"}:
        lang = "es"
    request.session["lang"] = lang
    return lang

